# Generated by Django 4.0.4 on 2022-06-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='clicks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
