# Generated by Django 4.0.4 on 2022-06-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_alter_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='movie_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.movie'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='series_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movieapp.series'),
        ),
    ]
