# Generated by Django 4.0.4 on 2022-06-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
