# Generated by Django 4.0.4 on 2022-06-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_alter_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pricing_plan',
            field=models.CharField(blank=True, default='Free', max_length=100, null=True),
        ),
    ]
