# Generated by Django 4.0.4 on 2022-06-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_profile_comments_profile_creation_date_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comments',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
