# Generated by Django 4.0.4 on 2022-06-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0010_alter_movie_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='cat',
            field=models.CharField(default='movie', max_length=200),
        ),
    ]
