# Generated by Django 4.0.4 on 2022-06-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0011_series_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='cat',
            field=models.CharField(default='anime', max_length=200),
        ),
    ]
