# Generated by Django 4.0.4 on 2022-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0013_alter_episode_episode_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='sub_title_file',
            field=models.FileField(blank=True, null=True, upload_to='movie/subtitles'),
        ),
        migrations.AddField(
            model_name='episode',
            name='sub_title_lang',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='sub_title_file',
            field=models.FileField(blank=True, null=True, upload_to='movie/subtitles'),
        ),
        migrations.AddField(
            model_name='movie',
            name='sub_title_lang',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
