# Generated by Django 4.0.4 on 2022-07-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0015_episode_sub_title_file2_episode_sub_title_lang2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='srclang',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='srclang2',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
