# Generated by Django 4.0.4 on 2022-07-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0017_movie_srclang_movie_srclang2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='sub_title_file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='sub_title_file2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sub_title_file',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sub_title_file2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
